//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace butterfly.service.schedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleEntry
    {
        public System.DateTime Time { get; set; }
        public string ParamId { get; set; }
    }
}
